<?php

namespace Database\Seeders;

use App\Models\Advertisement;
use Illuminate\Database\Seeder;

class AdvertisementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ads = [
            [
                'name' => 'Header Banner Ad 1',
                'placement' => 'header_top',
                'type' => 'banner',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/728x90/3498db/ffffff?text=Header+Banner+Ad',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Navigation Sticky Ad',
                'placement' => 'navigation_sticky',
                'type' => 'sticky',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/728x90/2ecc71/ffffff?text=Navigation+Sticky',
                'device_target' => 'desktop',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Homepage Top Ad',
                'placement' => 'homepage_top',
                'type' => 'banner',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/728x90/e74c3c/ffffff?text=Homepage+Top',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Sidebar Medium Rectangle Ad',
                'placement' => 'sidebar_medium_rectangle',
                'type' => 'sidebar',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x250/9b59b6/ffffff?text=Sidebar+Rectangle',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Sidebar Half Page Ad',
                'placement' => 'sidebar_half_page',
                'type' => 'sidebar',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x600/f39c12/ffffff?text=Sidebar+Half+Page',
                'device_target' => 'desktop',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Article 2nd Paragraph Ad',
                'placement' => 'article_2nd_paragraph',
                'type' => 'inline',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x250/1abc9c/ffffff?text=Article+2nd',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Article Middle Ad',
                'placement' => 'article_middle',
                'type' => 'inline',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x250/34495e/ffffff?text=Article+Middle',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Article Conclusion Ad',
                'placement' => 'article_conclusion',
                'type' => 'inline',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x250/e67e22/ffffff?text=Article+Conclusion',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Below Article Ad',
                'placement' => 'below_article',
                'type' => 'banner',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/728x90/c0392b/ffffff?text=Below+Article',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Footer Banner Ad',
                'placement' => 'footer_banner',
                'type' => 'banner',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/728x90/16a085/ffffff?text=Footer+Banner',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Between News Listings Ad',
                'placement' => 'between_news_listings',
                'type' => 'inline',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/300x250/8e44ad/ffffff?text=Between+News',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => true,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Sticky Sidebar Left Ad',
                'placement' => 'sticky_sidebar_left',
                'type' => 'sticky',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/160x600/27ae60/ffffff?text=Sticky+Left',
                'device_target' => 'desktop',
                'start_date' => now(),
                'is_active' => false,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Sticky Sidebar Right Ad',
                'placement' => 'sticky_sidebar_right',
                'type' => 'sticky',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/160x600/2980b9/ffffff?text=Sticky+Right',
                'device_target' => 'desktop',
                'start_date' => now(),
                'is_active' => false,
                'display_order' => 1,
                'created_by' => 1,
            ],
            [
                'name' => 'Popup/Interstitial Ad',
                'placement' => 'popup_interstitial',
                'type' => 'popup',
                'ad_source' => 'offline',
                'ad_url' => 'https://example.com',
                'image_url' => 'https://via.placeholder.com/400x300/c0392b/ffffff?text=Popup+Ad',
                'device_target' => 'all',
                'start_date' => now(),
                'is_active' => false,
                'display_order' => 1,
                'created_by' => 1,
            ],
        ];

        foreach ($ads as $ad) {
            Advertisement::updateOrCreate(
                ['name' => $ad['name']],
                $ad
            );
        }
    }
}
