/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './resources/views/public/**/*.blade.php',
    './resources/views/sitemap.blade.php',
    './resources/views/news-sitemap.blade.php',
    './resources/views/rss-feed.blade.php',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary': '#bb0112',
        'surface-container-low': '#f6f3f5',
        'on-secondary': '#ffffff',
        'background': '#fcf8fa',
        'inverse-surface': '#303032',
        'on-surface': '#1b1b1d',
        'primary-fixed': '#dae2fd',
        'news-red-accent': '#B91C1C',
        'inverse-on-surface': '#f3f0f2',
        'surface-container-high': '#eae7e9',
        'secondary-fixed-dim': '#ffb4ab',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#bec6e0',
        'primary': '#000000',
        'primary-fixed-dim': '#bec6e0',
        'tertiary': '#000000',
        'on-primary': '#ffffff',
        'news-blue-dark': '#1E293B',
        'primary-container': '#131b2e',
        'surface-container': '#f0edef',
        'secondary-fixed': '#ffdad6',
        'on-surface-variant': '#45464d',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#410002',
        'on-background': '#1b1b1d',
        'surface-tint': '#565e74',
        'surface-bright': '#fcf8fa',
        'surface-dim': '#dcd9db',
        'on-primary-container': '#7c839b',
        'secondary-container': '#e02928',
        'on-primary-fixed': '#131b2e',
        'outline-variant': '#c6c6cd',
        'surface': '#fcf8fa',
        'tertiary-fixed': '#fcdeb5',
        'on-error': '#ffffff',
        'surface-variant': '#e4e2e4',
        'on-tertiary-container': '#98805d',
        'surface-container-highest': '#e4e2e4',
        'border-subtle': '#E2E8F0',
        'on-secondary-container': '#fffbff',
        'tertiary-fixed-dim': '#dec29a',
        'tertiary-container': '#271901',
        'outline': '#76777d',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#3f465c',
        'surface-muted': '#F8FAFC',
        'on-tertiary-fixed': '#271901',
        'on-tertiary-fixed-variant': '#574425',
        'on-secondary-fixed-variant': '#93000b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '100%',
        'stack-lg': '2rem',
        'stack-sm': '0.5rem',
        'gutter': '2rem',
        'section-padding': '4rem',
        'stack-md': '1rem',
      },
      fontFamily: {
        'body-main': ['Libre Franklin'],
        'body-sm': ['Libre Franklin'],
        'display-breaking': ['SolaimanLipi'],
        'headline-lg': ['SolaimanLipi'],
        'label-caps': ['Work Sans'],
        'headline-md': ['SolaimanLipi'],
        'meta-data': ['Work Sans'],
        'headline-lg-mobile': ['SolaimanLipi'],
      },
      fontSize: {
        'body-main': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-breaking': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
        'meta-data': ['13px', { lineHeight: '1', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
